displayName: eShopOnWebLoadTeting
testPlan: url-test.json
description: ''
engineInstances: 1
testId: b9e1b5bf-3a8e-4528-a5bb-49541bb6600c
testType: URL
splitAllCSVs: False
referenceIdentities:
- kind: KeyVault
  type: SystemAssigned
- kind: Metrics
  type: SystemAssigned
autoStop:
  errorPercentage: 90
  timeWindow: 60
  maximumVirtualUsersPerEngine: 5000
