displayName: URLTest
testPlan: url_test.jmx
description: ''
engineInstances: 2
testId: b9e1b5bf-3a8e-4528-a5bb-49541bb6600c
testType: JMX
splitAllCSVs: False
failureCriteria:
- p90(response_time_ms) > 4000
- percentage(error) > 10
autoStop:
  errorPercentage: 80
  timeWindow: 120
