name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP: Hackathon
  LOCATION: westeurope
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: 539fbb79-2988-4831-927f-e46e465c06b1
  WEBAPP_NAME: eshoponweb-webapp-Hackathon

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: "preview"

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp
          cd ${{ env.DOTNET_ROOT }}/myapp
          zip -r ../app.zip .

      - name: Upload artifact (webapp)
        uses: actions/upload-artifact@v5
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/app.zip

      - name: Upload artifact (bicep)
        uses: actions/upload-artifact@v5
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: Development
    steps:
      - name: Download artifact (webapp)
        uses: actions/download-artifact@v6
        with:
          name: .net-app
          path: .net-app

      - name: Download artifact (bicep)
        uses: actions/download-artifact@v6
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infra (Bicep)
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: bicep-template/webapp.bicep
          parameters: "webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }}"
          failOnStdErr: false

      - name: Publish Website to WebApp (CLI)
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name ${{ env.WEBAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --src-path .net-app/app.zip \
              --type zip
